version: "3.8"

services:

  # Our Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./linkedin
      target: development
    command: npm run start
    volumes:
      - ./linkedin:/app
      - /app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  # Our Postgres Database for NestJS to connect to
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: linkedin
      PORT: 5432

        # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./Linkedinbackend
      target: development
    volumes:
      - ./Linkedinbackend:/app
      - /app/node_modules/
    command: bash -c "sleep 20 && npm run start"
    depends_on: 
      - postgres 
    environment:
     - POSTGRES_HOST=postgres
     - POSTGRES_PORT=5432
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Admin
     - POSTGRES_DATABASE=linkedin
     - JWT_SECRET=jwtsecret
     - PORT=3000

      # DATABASE_URL: postgres://postgres:Admin@postgres:5432/linkedin
      # NODE_ENV: development
      # JWT_SECRET: jwtsecret
      # PORT: 3000
     
    
